### ISSUE TITLE
Matlab Engine not installing

### ISSUE THREAD

**Issue by devShaurya** [HanHan55/Graph2plan#1]
![Annotation 2020-07-02 113759](https://user-images.githubusercontent.com/40660207/86322354-71c37400-bc58-11ea-8fcf-9c0cce9ce852.png)

Hi! Great work btw. I have issue in installing matlab engine with python 3.7.  I have attached a photo of the error. Could you please specify how were you able to install it.

**Comment by zzilch** [comment]
Thank you for you attention. I think your matlab version is lower than we used. We used Matlab 2019b.

**Comment by zzilch** [comment]
Thank you for your attention. I think your matlab version is lower than we used. We used Matlab 2019b.
