### ISSUE TITLE
Missing file: /retrieval/tf_train.npy

### ISSUE THREAD

**Issue by Mistrymm7** [HanHan55/Graph2plan#10]
tf_train.npy is not available.

![image](https://user-images.githubusercontent.com/7644450/111264985-6ea9c180-85f6-11eb-9eb2-672337573122.png)

![image](https://user-images.githubusercontent.com/7644450/111265031-8123fb00-85f6-11eb-88ac-991be2dbd3b6.png)

![image](https://user-images.githubusercontent.com/7644450/111265140-a7e23180-85f6-11eb-96c3-efe6d1eacf91.png)

**Comment by zzilch** [comment]
Download and unzip the data provided in part 1.

**Comment by Mistrymm7** [comment]
That worked. Thank you.
