### ISSUE TITLE
What's the meaning of r in rEdge?

### ISSUE THREAD

**Issue by chenxinl** [HanHan55/Graph2plan#11]
Hi!
      I can't get the meaning of r in rEdge where 'rEdge: (u,v,r), room indices and relative position(u relative to v)'.
Meanwhile, it is not used in the floorplan.py, see 101: 'for u, v, _ in self.data.rEdge:', but I want to know the relation in rooms, so can you explain the definition of r in rEdge? 
      Thanks a lot.

**Comment by zzilch** [comment]
For the edge relation, please refer to Fig.3 (c) in the paper.
We compute the edge relation on-the-fly because we augment the data by random rotation and flip when training.
