### ISSUE TITLE
Getting IndexError: index 208 is out of bounds for acis 0 with size 208, while training

### ISSUE THREAD

**Issue by LucaJeevanjee** [HanHan55/Graph2plan#15]
Hello, I am receiving this issue as well,
The index in which the error occurs changes when the batch size and number of workers is changed.

![image](https://user-images.githubusercontent.com/30826343/134963833-c000b80f-2f61-4251-a959-5df9ace11d31.png)

This is the log from when it crashes.
Looks like either training data: 27184 or 75591
Thanks in advance!

_Originally posted by @LucaJeevanjee in https://github.com/HanHan55/Graph2plan/issues/7#issuecomment-928155022_

**Comment by zzilch** [comment]
Sorry, I forgot to update the code for that issue. Try the latest commit. It just add some clamping in line 162 of `floorplan.py`.

**Comment by LucaJeevanjee** [comment]
> Sorry, I forgot to update the code for that issue. Try the latest commit. It just add some clamping in line 162 of `floorplan.py`.

Awesome, thanks, its working now and congrats, awesome project.

Do you have any suggestions to stop me from running out of memory when training? 

I'm using the multi gpu but CUDA is running out of memory on GPU 0 after the 2nd epoch. I'm using batch size 8 and 4 workers
