### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [HanHan55/Graph2plan#19]
Hi

Thanks for your effort on this great repo. 

I get the above error when i run: ` python3 manage.py runserver 0.0.0.0:8000
`
I am using python==3.9
Here is the terminal log:
"""
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
iunie 17, 2023 - 07:01:15
Django version 4.2.2, using settings 'House.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Not Found: /
[17/Jun/2023 07:01:32] "GET / HTTP/1.1" 404 3230
"""
Here is the web log:
![Screenshot from 2023-06-17 09-56-19](https://github.com/HanHan55/Graph2plan/assets/112307557/5286e14f-fc17-44ee-98e2-5bc74b9a44aa)

What am I doing wrong? any insight?
Thanks in advance

**Comment by zzilch** [comment]
http://127.0.0.1:8000/home
