### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by wanghangpsu** [HanHan55/Graph2plan#2]
Hi, thanks for the great work @ruizhenh 

I am trying to run the code on linux system. when I run

python manage.py runserver 0.0.0.0:8000

it gives the following error:

manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

I cant understand what is happening. Any help?

Thanks

**Comment by zzilch** [comment]
Sorry, there is a fatal bug when using Matlab and pytorch<1.5.0 together on Linux. 
Please install the pytorch 1.5.0+ to use the interface.
