### ISSUE TITLE
Error in GUI and Test file

### ISSUE THREAD

**Issue by devShaurya** [HanHan55/Graph2plan#3]
Hi, I was trying to run the GUI using `python manage.py runserver`. I am able to load images from Interface\House\static\Data\Img\ but when I click the "Transfer" button, the programme is giving me FileNotFound error. "Generate" and "Save" button don't seem to give any output. I am not able to .mat files for any of the layouts. Could you please suggest how to remove this error? Could you also tell how to test the trained model without using the GUI? Lastly how to use "Graph" and "Layout" buttons which appear after clicking the "Transfer" button
![image](https://user-images.githubusercontent.com/40660207/87559667-37d28300-c6d8-11ea-8f22-748a8328ca21.png)

**Comment by HanHan55** [comment]
Regarding this error,the data zip has been updated and you need to place the downloaded data under the same folder in the project code according to the folder name. And if you want to test the trained model without using the GUI,You can test the trained model  using the code in PostProcessing directory in the lastest commit. Finally, if you click the  "Graph" button, the graph will disappear and the layout will be displayed.Accordingly, by clicking the "Layout" button, the layout disappears and only the graph  is displayed.

**Comment by devShaurya** [comment]
Thanks for quick response. I will try your solution. And great work btw.
