### ISSUE TITLE
Preprocessing for our own dataset

### ISSUE THREAD

**Issue by devShaurya** [HanHan55/Graph2plan#4]
Hi, I read your paper. You have mentioned the preprocessing steps regarding generating graphs for each of the floorplan present in the RPlan dataset. Could you please share the code regarding it?

**Comment by zzilch** [comment]
We release a [toolbox ](https://github.com/zzilch/RPLAN-Toolbox) for exploring the [PRLAN](http://staff.ustc.edu.cn/~fuxm/projects/DeepLayout/index.html) dataset. Most of the preprocessing and postprocessing steps are included in the toolbox.

**Comment by devShaurya** [comment]
Thanks for the quick reply. Great work @ruizhenh @HanHan55
